// <auto-generated />
using System;
using CareFlowAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareFlowAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005075013_AddFullNameToUser")]
    partial class AddFullNameToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Idle");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("AgentWorkflows");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Tentative");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            FullName = "Dr. Robert Smith",
                            IsActive = true,
                            Specialization = "General Practitioner"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Email = "neuro@careflow.ai",
                            FullName = "Dr. Alice Wong",
                            IsActive = true,
                            Specialization = "Neurologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Email = "cardio@careflow.ai",
                            FullName = "Dr. James Bond",
                            IsActive = true,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Email = "pulmon@careflow.ai",
                            FullName = "Dr. Sarah Connor",
                            IsActive = true,
                            Specialization = "Pulmonologist"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73347ad7-9f3d-4d44-af41-f2cf190e0219"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("24ebc8d4-2080-47dd-9e70-b74dcd810ff5"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("6599d5d9-a3b1-405a-ac24-15be148c32b3"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e70dcad6-4d46-47df-9451-eaf9de8c7a99"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("4595f0eb-90a5-411b-bf6d-952b0d5df842"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("8f836e61-83cf-4a8e-92ef-79983b07ad15"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3f625883-1a0b-46bb-9e1a-e22e4a5e485d"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0a5e9ac6-b669-4e9f-a09d-55b461f9c5c3"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a4549331-ee20-4545-9263-d9a57b279dd3"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("44e4c71b-7f06-4d27-bcea-368aebe11283"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("b045f7c8-1cc5-4e50-a917-54c5d243efa0"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("b370f28f-fe81-4426-85df-44edb3afb16c"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("ae3e89de-3f28-43de-90b3-7913f6a1d8d4"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("4a153134-46f7-4021-a3c4-d1f78b244879"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("8ca9c78e-09eb-4aa8-ae35-b8f7bae5cb80"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("ec555e4b-d89f-4cba-bd6d-a1046accb827"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("da4e3828-8950-42e3-9803-fefbae0ed8bf"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7f9e966c-d3f8-46f9-8380-e5dc8f3d5005"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c2111a82-4e32-4985-a499-9bd22d86799f"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3fa0e8f5-5ee8-405c-a24b-9af70bd3aa0d"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a4c098af-c4d9-4ae4-ba9b-91a71c721dde"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c0e85055-a76c-4641-87de-e38d1795f398"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("6b74651a-342f-4244-9858-c2be8da9b23c"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0362aed7-94a2-4084-b6c4-3fa065793b48"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3528ce1f-0cc4-454a-bbee-f765209d458a"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("35e0a9ea-4c51-4374-951b-6a33e0e5aefe"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0d4876f0-8854-4aec-85de-813c5b395f31"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("12d0fe59-7bd8-4c28-9f78-02c9940fa95a"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalHistorySummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            BloodGroup = "O+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 50, 13, 240, DateTimeKind.Utc).AddTicks(5490),
                            DateOfBirth = new DateOnly(1985, 3, 12),
                            FullName = "Sarah Jenkins",
                            IsActive = true,
                            MedicalHistorySummary = "No known allergies. Previous appendectomy."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            BloodGroup = "A-",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 50, 13, 240, DateTimeKind.Utc).AddTicks(5490),
                            DateOfBirth = new DateOnly(1972, 11, 5),
                            FullName = "Marcus Thorne",
                            IsActive = true,
                            MedicalHistorySummary = "Type 2 Diabetes, Hypertension."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            BloodGroup = "B+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 50, 13, 240, DateTimeKind.Utc).AddTicks(5500),
                            DateOfBirth = new DateOnly(1990, 7, 22),
                            FullName = "Emily Chen",
                            IsActive = true,
                            MedicalHistorySummary = "Asthma, treated with inhalers."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            BloodGroup = "O-",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 50, 13, 240, DateTimeKind.Utc).AddTicks(5500),
                            DateOfBirth = new DateOnly(1950, 1, 30),
                            FullName = "David Alaba",
                            IsActive = true,
                            MedicalHistorySummary = "Coronary artery disease, pacemaker fitted 2018."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BloodGroup = "AB+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 50, 13, 240, DateTimeKind.Utc).AddTicks(5510),
                            DateOfBirth = new DateOnly(2005, 9, 14),
                            FullName = "Fiona Gallagher",
                            IsActive = true,
                            MedicalHistorySummary = "None."
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSafetyCheckResult")
                        .HasColumnType("text");

                    b.Property<string>("AiSafetyStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("IssuedByDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("NotificationChannel")
                        .HasColumnType("text");

                    b.Property<string>("NotificationFailureReason")
                        .HasColumnType("text");

                    b.Property<int>("NotificationRetryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageAttachments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TentativeAppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("TriageRecords");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AgentWorkflowStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SymptomsAtReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowStateId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageReviewHistories");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 50, 13, 240, DateTimeKind.Utc).AddTicks(5440),
                            Email = "admin@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 50, 13, 240, DateTimeKind.Utc).AddTicks(5440),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Doctor",
                            Username = "doctor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 50, 13, 240, DateTimeKind.Utc).AddTicks(5450),
                            Email = "staff@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("OccupiedBeds")
                        .HasColumnType("integer");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Capacity = 50,
                            OccupiedBeds = 45,
                            WardNumber = "G-01",
                            WardType = "General"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Capacity = 15,
                            OccupiedBeds = 12,
                            WardNumber = "I-01",
                            WardType = "ICU"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Capacity = 30,
                            OccupiedBeds = 20,
                            WardNumber = "M-01",
                            WardType = "Maternity"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacity = 25,
                            OccupiedBeds = 10,
                            WardNumber = "P-01",
                            WardType = "Pediatrics"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "PatientProfile")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientProfile");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("AgentWorkflows")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.AgentWorkflowState", "AgentWorkflowState")
                        .WithMany()
                        .HasForeignKey("AgentWorkflowStateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflowState");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Navigation("AgentWorkflows");

                    b.Navigation("ReviewHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
