// <auto-generated />
using System;
using CareFlowAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareFlowAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005100645_SeedPenicillin")]
    partial class SeedPenicillin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Idle");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("AgentWorkflows");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Tentative");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            FullName = "Dr. Robert Smith",
                            IsActive = true,
                            Specialization = "General Practitioner"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Email = "neuro@careflow.ai",
                            FullName = "Dr. Alice Wong",
                            IsActive = true,
                            Specialization = "Neurologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Email = "cardio@careflow.ai",
                            FullName = "Dr. James Bond",
                            IsActive = true,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Email = "pulmon@careflow.ai",
                            FullName = "Dr. Sarah Connor",
                            IsActive = true,
                            Specialization = "Pulmonologist"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5197fbe8-f54a-4d87-bd7b-82b93d36e111"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3b06256a-d942-4f3b-ad7e-4ba6f9eed48d"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c3352b19-8c12-4a32-88fa-2fa16bb79c99"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7ac29be8-eee8-4203-be5e-652a6cdb6dc7"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("269f87ff-57ca-4ef0-a1dd-581f5566b306"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("01b987f2-74c8-41a3-8847-260be27d2607"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a7eb8897-8c4f-4afd-a156-73ce9caad686"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("f4e656d7-65d9-4ae9-beaa-897f57ba779f"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7260440d-6353-4c1e-a5f0-49326f42e993"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("682de52a-65a8-4f98-b9ee-6fe3ac81b76b"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("6224f692-78e7-48f6-a55b-eb8bcc9b9ae7"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("587cd0b2-95c4-433f-92dc-b9188ec5db80"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("44fb9971-7d4e-40b4-9d47-7c2b36338ae2"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a8cb586b-a2d5-4d19-978b-ffee0fe5d7af"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("853a3600-cdb2-4b80-bfc6-7bed651c80a3"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("16bff826-e518-4fad-9215-d40b128efe4f"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("9c9f8f80-c8b7-4640-8af7-eab067e76a18"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("36b59332-ca20-4508-aca1-e1e137dedb46"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("8d88328d-01d4-4de3-9080-db2e4007c2bb"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7cb01284-60b0-4880-809b-004b8527706f"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("872cb9ab-0875-4181-af32-75194d3bfa63"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e45e97fd-d61c-4370-85b6-aead3f9e9085"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("b1744bb9-a343-4325-be78-40b7667e844d"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("d7ca6639-46e4-47c3-b1c3-7ceb1e4a780b"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("99215c53-cc5d-4a9b-b71e-d33f4cc6111d"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("210b0a1d-3f73-4dd3-ad0c-cc6a363153c0"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("bb106138-c2dd-4e96-8aeb-0f574300e117"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e4dfd2e5-b8df-4615-a78c-e8383d4f67d1"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            Category = "Antibiotic",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3320),
                            Description = "Used to treat bacterial infections.",
                            ExpiryDate = new DateOnly(2028, 1, 1),
                            IsActive = true,
                            Manufacturer = "PharmaCorp",
                            Name = "Amoxicillin 500mg",
                            ReorderLevel = 100,
                            StockQuantity = 1000,
                            UnitPrice = 15.00m,
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3320)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            Category = "Painkiller",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3330),
                            Description = "Nonsteroidal anti-inflammatory drug (NSAID).",
                            ExpiryDate = new DateOnly(2027, 6, 30),
                            IsActive = true,
                            Manufacturer = "HealthLife",
                            Name = "Ibuprofen 400mg",
                            ReorderLevel = 50,
                            StockQuantity = 500,
                            UnitPrice = 8.50m,
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3330)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            Category = "Gastrointestinal",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3330),
                            Description = "Proton pump inhibitor for acid reflux.",
                            ExpiryDate = new DateOnly(2026, 12, 15),
                            IsActive = true,
                            Manufacturer = "GastroMed",
                            Name = "Omeprazole 20mg",
                            ReorderLevel = 30,
                            StockQuantity = 300,
                            UnitPrice = 22.00m,
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3330)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666664"),
                            Category = "Blood Thinner",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3340),
                            Description = "Used to reduce the risk of heart attacks.",
                            ExpiryDate = new DateOnly(2029, 3, 22),
                            IsActive = true,
                            Manufacturer = "CardioCare",
                            Name = "Aspirin 81mg",
                            ReorderLevel = 80,
                            StockQuantity = 800,
                            UnitPrice = 5.00m,
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3340)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666665"),
                            Category = "Antibiotic",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3340),
                            Description = "Used to treat bacterial infections.",
                            ExpiryDate = new DateOnly(2028, 5, 10),
                            IsActive = true,
                            Manufacturer = "PharmaCorp",
                            Name = "Penicillin V Potassium 250mg",
                            ReorderLevel = 50,
                            StockQuantity = 400,
                            UnitPrice = 12.00m,
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3340)
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalHistorySummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            BloodGroup = "O+",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3270),
                            DateOfBirth = new DateOnly(1985, 3, 12),
                            FullName = "Sarah Jenkins",
                            IsActive = true,
                            MedicalHistorySummary = "No known allergies. Previous appendectomy."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            BloodGroup = "A-",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3280),
                            DateOfBirth = new DateOnly(1972, 11, 5),
                            FullName = "Marcus Thorne",
                            IsActive = true,
                            MedicalHistorySummary = "Type 2 Diabetes, Hypertension."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            BloodGroup = "B+",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3300),
                            DateOfBirth = new DateOnly(1990, 7, 22),
                            FullName = "Emily Chen",
                            IsActive = true,
                            MedicalHistorySummary = "Asthma, treated with inhalers."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            BloodGroup = "O-",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3300),
                            DateOfBirth = new DateOnly(1950, 1, 30),
                            FullName = "David Alaba",
                            IsActive = true,
                            MedicalHistorySummary = "Coronary artery disease, pacemaker fitted 2018."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BloodGroup = "AB+",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3300),
                            DateOfBirth = new DateOnly(2005, 9, 14),
                            FullName = "Fiona Gallagher",
                            IsActive = true,
                            MedicalHistorySummary = "None."
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSafetyCheckResult")
                        .HasColumnType("text");

                    b.Property<string>("AiSafetyStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("IssuedByDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("NotificationChannel")
                        .HasColumnType("text");

                    b.Property<string>("NotificationFailureReason")
                        .HasColumnType("text");

                    b.Property<int>("NotificationRetryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageAttachments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TentativeAppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("TriageRecords");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AgentWorkflowStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SymptomsAtReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowStateId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageReviewHistories");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3220),
                            Email = "admin@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3230),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Doctor",
                            Username = "doctor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 10, 5, 10, 6, 45, 264, DateTimeKind.Utc).AddTicks(3230),
                            Email = "staff@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("OccupiedBeds")
                        .HasColumnType("integer");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Capacity = 50,
                            OccupiedBeds = 45,
                            WardNumber = "G-01",
                            WardType = "General"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Capacity = 15,
                            OccupiedBeds = 12,
                            WardNumber = "I-01",
                            WardType = "ICU"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Capacity = 30,
                            OccupiedBeds = 20,
                            WardNumber = "M-01",
                            WardType = "Maternity"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacity = 25,
                            OccupiedBeds = 10,
                            WardNumber = "P-01",
                            WardType = "Pediatrics"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "PatientProfile")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientProfile");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("AgentWorkflows")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.AgentWorkflowState", "AgentWorkflowState")
                        .WithMany()
                        .HasForeignKey("AgentWorkflowStateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflowState");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Navigation("AgentWorkflows");

                    b.Navigation("ReviewHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
