// <auto-generated />
using System;
using CareFlowAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareFlowAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005072614_FixPatientIsActiveDefault")]
    partial class FixPatientIsActiveDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Idle");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("AgentWorkflows");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Tentative");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            FullName = "Dr. Robert Smith",
                            IsActive = true,
                            Specialization = "General Practitioner"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Email = "neuro@careflow.ai",
                            FullName = "Dr. Alice Wong",
                            IsActive = true,
                            Specialization = "Neurologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Email = "cardio@careflow.ai",
                            FullName = "Dr. James Bond",
                            IsActive = true,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Email = "pulmon@careflow.ai",
                            FullName = "Dr. Sarah Connor",
                            IsActive = true,
                            Specialization = "Pulmonologist"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0bc037a-2dc1-4ccc-afc1-b56bdc258b34"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("ab585e6d-9910-4eaa-88b0-f27364edc332"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("5a514277-3d6f-4745-9719-5cc36e9f74f2"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("2c624300-19b6-4c44-ad07-4651faf069df"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("01c320c4-f45c-4bef-99cb-189cb0aa09cb"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0ce604ca-af1e-4450-96cd-f080d1f18163"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("ff0a36a2-5af6-4a42-aaa7-03d4dad4e309"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("9dd77ef0-7db3-4804-a19a-245928dbafdd"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("cff331dd-21b5-4cca-9daa-f66c91874471"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("b477fc2f-fa42-4828-af5a-dbdfc9dd3578"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("becd0746-48e9-48fb-86fa-fc3202ab444a"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("32ed715a-5808-442b-99b1-4b5752d57f67"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("15f983f0-ff62-41f7-9e0f-8dc484706516"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("52c6bdd6-fd1f-42f2-8cc1-3dd54593b0f4"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0a12b148-f8bf-4954-949c-5613516fa125"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c1140d52-ca79-4e4e-aaf5-7a08a6492420"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("6865ff03-096c-4a66-96f6-19da1b1229b8"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e6088ec4-5774-4337-a634-1f7f4c76d1c3"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("9751b624-ce25-4ce3-b61c-6b132ae2e5f0"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("571407d7-1464-49e0-bb3a-bc33fd38a33e"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("048468aa-a1bf-4a7a-b5d8-5fc779a49ed3"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("5064ba46-f3b0-4ff7-8ad7-6091e4bb4874"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a222ca5b-f734-4a41-84de-74e6cc368efa"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("6cb02329-6ad8-4135-895e-1283ce175dd6"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("d90223f4-60c7-40a0-a231-d0d2dd736a5e"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("1787a272-4b08-4795-952f-49aee1724b79"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("33249204-565a-43c0-b4f1-7a42878ad5c9"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0ced5306-f445-4284-9d0f-9ce45dcdd6e2"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalHistorySummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            BloodGroup = "O+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 26, 14, 657, DateTimeKind.Utc).AddTicks(8790),
                            DateOfBirth = new DateOnly(1985, 3, 12),
                            FullName = "Sarah Jenkins",
                            IsActive = true,
                            MedicalHistorySummary = "No known allergies. Previous appendectomy."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            BloodGroup = "A-",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 26, 14, 657, DateTimeKind.Utc).AddTicks(8800),
                            DateOfBirth = new DateOnly(1972, 11, 5),
                            FullName = "Marcus Thorne",
                            IsActive = true,
                            MedicalHistorySummary = "Type 2 Diabetes, Hypertension."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            BloodGroup = "B+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 26, 14, 657, DateTimeKind.Utc).AddTicks(8800),
                            DateOfBirth = new DateOnly(1990, 7, 22),
                            FullName = "Emily Chen",
                            IsActive = true,
                            MedicalHistorySummary = "Asthma, treated with inhalers."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            BloodGroup = "O-",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 26, 14, 657, DateTimeKind.Utc).AddTicks(8800),
                            DateOfBirth = new DateOnly(1950, 1, 30),
                            FullName = "David Alaba",
                            IsActive = true,
                            MedicalHistorySummary = "Coronary artery disease, pacemaker fitted 2018."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BloodGroup = "AB+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 26, 14, 657, DateTimeKind.Utc).AddTicks(8810),
                            DateOfBirth = new DateOnly(2005, 9, 14),
                            FullName = "Fiona Gallagher",
                            IsActive = true,
                            MedicalHistorySummary = "None."
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSafetyCheckResult")
                        .HasColumnType("text");

                    b.Property<string>("AiSafetyStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("IssuedByDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("NotificationChannel")
                        .HasColumnType("text");

                    b.Property<string>("NotificationFailureReason")
                        .HasColumnType("text");

                    b.Property<int>("NotificationRetryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageAttachments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TentativeAppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("TriageRecords");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AgentWorkflowStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SymptomsAtReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowStateId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageReviewHistories");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 26, 14, 657, DateTimeKind.Utc).AddTicks(8740),
                            Email = "admin@careflow.ai",
                            Password = "password",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 26, 14, 657, DateTimeKind.Utc).AddTicks(8740),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            Password = "password",
                            Role = "Doctor",
                            Username = "doctor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 26, 14, 657, DateTimeKind.Utc).AddTicks(8750),
                            Email = "staff@careflow.ai",
                            Password = "password",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("OccupiedBeds")
                        .HasColumnType("integer");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Capacity = 50,
                            OccupiedBeds = 45,
                            WardNumber = "G-01",
                            WardType = "General"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Capacity = 15,
                            OccupiedBeds = 12,
                            WardNumber = "I-01",
                            WardType = "ICU"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Capacity = 30,
                            OccupiedBeds = 20,
                            WardNumber = "M-01",
                            WardType = "Maternity"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacity = 25,
                            OccupiedBeds = 10,
                            WardNumber = "P-01",
                            WardType = "Pediatrics"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "PatientProfile")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientProfile");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("AgentWorkflows")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.AgentWorkflowState", "AgentWorkflowState")
                        .WithMany()
                        .HasForeignKey("AgentWorkflowStateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflowState");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Navigation("AgentWorkflows");

                    b.Navigation("ReviewHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
