// <auto-generated />
using System;
using CareFlowAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareFlowAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005095601_SeedMedicines")]
    partial class SeedMedicines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Idle");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("AgentWorkflows");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Tentative");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            FullName = "Dr. Robert Smith",
                            IsActive = true,
                            Specialization = "General Practitioner"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Email = "neuro@careflow.ai",
                            FullName = "Dr. Alice Wong",
                            IsActive = true,
                            Specialization = "Neurologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Email = "cardio@careflow.ai",
                            FullName = "Dr. James Bond",
                            IsActive = true,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Email = "pulmon@careflow.ai",
                            FullName = "Dr. Sarah Connor",
                            IsActive = true,
                            Specialization = "Pulmonologist"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9726a91-cd94-4abd-859f-cb49113ea99e"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3c15b6bc-23d1-4343-ad55-be9925a13358"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c445d0bc-946e-43c9-8fce-bbcba7ba014a"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a80248ac-abab-45d4-a1ce-7fb4b4502802"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("2819004b-3e86-4e7f-8423-c0f0fe356dcf"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("98599668-af7d-4a98-8f09-bc869fa9c076"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("9020f39c-9d1a-4379-8ce5-3b6edfa7cee1"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3501dc70-aca3-45e0-81eb-fc3a6350ef1e"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c5920d9a-6eb3-4542-821f-677bb2fab502"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0a2f21ef-f9fb-49b1-a741-c68d27f9b3b4"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e5cf9b29-282e-46d5-9da5-a22dec78bbdc"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("84e72f94-dbb2-433d-b0ef-71a92c7697b8"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("fe8df537-6d0e-4f4d-9937-ef6115d6ba9d"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("80346575-892f-48e7-a936-60ed416167c8"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3c84cb2a-98f4-40df-9000-31cba4c0a95c"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("72a0be44-044c-4e6d-a005-bf01e551ba67"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e4b12814-9fb1-46d3-a18b-29201d0e4c16"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("b8f7a20d-8f83-4072-ad9f-c5ff295770f0"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c07f5da0-f9a5-48ca-b66a-f03ec657c695"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3de742d0-5d35-404d-a117-1e5c338cb7b3"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("486235a9-0f42-4ece-8bdd-c9ff69dc463d"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("5587c168-4dc1-46d2-905e-8d9c8e5022e7"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("242b0a08-b76a-468b-a5de-ff47ba082853"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("1c39f8e6-0580-4505-a681-16aa3bd21624"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("ceba186a-4926-4002-a198-7cd40c0fa513"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c1c594ac-11af-4688-8f17-63c6fe001f4a"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("5d0d9e6b-843b-4b90-8a99-daa27bef8bd3"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7cc1ae7e-bb0e-4eba-a310-b83c41a75334"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            Category = "Antibiotic",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5110),
                            Description = "Used to treat bacterial infections.",
                            ExpiryDate = new DateOnly(2028, 1, 1),
                            IsActive = true,
                            Manufacturer = "PharmaCorp",
                            Name = "Amoxicillin 500mg",
                            ReorderLevel = 100,
                            StockQuantity = 1000,
                            UnitPrice = 15.00m,
                            UpdatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5110)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            Category = "Painkiller",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5120),
                            Description = "Nonsteroidal anti-inflammatory drug (NSAID).",
                            ExpiryDate = new DateOnly(2027, 6, 30),
                            IsActive = true,
                            Manufacturer = "HealthLife",
                            Name = "Ibuprofen 400mg",
                            ReorderLevel = 50,
                            StockQuantity = 500,
                            UnitPrice = 8.50m,
                            UpdatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5120)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            Category = "Gastrointestinal",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5130),
                            Description = "Proton pump inhibitor for acid reflux.",
                            ExpiryDate = new DateOnly(2026, 12, 15),
                            IsActive = true,
                            Manufacturer = "GastroMed",
                            Name = "Omeprazole 20mg",
                            ReorderLevel = 30,
                            StockQuantity = 300,
                            UnitPrice = 22.00m,
                            UpdatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5130)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666664"),
                            Category = "Blood Thinner",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5130),
                            Description = "Used to reduce the risk of heart attacks.",
                            ExpiryDate = new DateOnly(2029, 3, 22),
                            IsActive = true,
                            Manufacturer = "CardioCare",
                            Name = "Aspirin 81mg",
                            ReorderLevel = 80,
                            StockQuantity = 800,
                            UnitPrice = 5.00m,
                            UpdatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5130)
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalHistorySummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            BloodGroup = "O+",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5060),
                            DateOfBirth = new DateOnly(1985, 3, 12),
                            FullName = "Sarah Jenkins",
                            IsActive = true,
                            MedicalHistorySummary = "No known allergies. Previous appendectomy."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            BloodGroup = "A-",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5070),
                            DateOfBirth = new DateOnly(1972, 11, 5),
                            FullName = "Marcus Thorne",
                            IsActive = true,
                            MedicalHistorySummary = "Type 2 Diabetes, Hypertension."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            BloodGroup = "B+",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5070),
                            DateOfBirth = new DateOnly(1990, 7, 22),
                            FullName = "Emily Chen",
                            IsActive = true,
                            MedicalHistorySummary = "Asthma, treated with inhalers."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            BloodGroup = "O-",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5090),
                            DateOfBirth = new DateOnly(1950, 1, 30),
                            FullName = "David Alaba",
                            IsActive = true,
                            MedicalHistorySummary = "Coronary artery disease, pacemaker fitted 2018."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BloodGroup = "AB+",
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5100),
                            DateOfBirth = new DateOnly(2005, 9, 14),
                            FullName = "Fiona Gallagher",
                            IsActive = true,
                            MedicalHistorySummary = "None."
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSafetyCheckResult")
                        .HasColumnType("text");

                    b.Property<string>("AiSafetyStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("IssuedByDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("NotificationChannel")
                        .HasColumnType("text");

                    b.Property<string>("NotificationFailureReason")
                        .HasColumnType("text");

                    b.Property<int>("NotificationRetryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageAttachments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TentativeAppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("TriageRecords");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AgentWorkflowStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SymptomsAtReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowStateId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageReviewHistories");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5010),
                            Email = "admin@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5010),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Doctor",
                            Username = "doctor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 10, 5, 9, 56, 1, 44, DateTimeKind.Utc).AddTicks(5020),
                            Email = "staff@careflow.ai",
                            FullName = "",
                            Password = "password",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("OccupiedBeds")
                        .HasColumnType("integer");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Capacity = 50,
                            OccupiedBeds = 45,
                            WardNumber = "G-01",
                            WardType = "General"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Capacity = 15,
                            OccupiedBeds = 12,
                            WardNumber = "I-01",
                            WardType = "ICU"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Capacity = 30,
                            OccupiedBeds = 20,
                            WardNumber = "M-01",
                            WardType = "Maternity"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacity = 25,
                            OccupiedBeds = 10,
                            WardNumber = "P-01",
                            WardType = "Pediatrics"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "PatientProfile")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientProfile");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("AgentWorkflows")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.AgentWorkflowState", "AgentWorkflowState")
                        .WithMany()
                        .HasForeignKey("AgentWorkflowStateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflowState");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Navigation("AgentWorkflows");

                    b.Navigation("ReviewHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
