// <auto-generated />
using System;
using CareFlowAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareFlowAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005073828_RemoveStaffWithoutEmail")]
    partial class RemoveStaffWithoutEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Idle");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("AgentWorkflows");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Tentative");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            FullName = "Dr. Robert Smith",
                            IsActive = true,
                            Specialization = "General Practitioner"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Email = "neuro@careflow.ai",
                            FullName = "Dr. Alice Wong",
                            IsActive = true,
                            Specialization = "Neurologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Email = "cardio@careflow.ai",
                            FullName = "Dr. James Bond",
                            IsActive = true,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Email = "pulmon@careflow.ai",
                            FullName = "Dr. Sarah Connor",
                            IsActive = true,
                            Specialization = "Pulmonologist"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2dbab48c-fcf9-4bf1-9b67-ed70c2048956"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("5cf58a49-4b5a-46a9-9e72-2d795b7f3965"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("d10ec423-cdca-4eee-b09c-2d977e82b0bc"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("1642dda9-90fc-45fd-9612-f83ff6d9893a"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("ddd431b8-8738-48d0-8cea-55c49eaa8b4c"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("aafa9621-ea85-4ad7-8b35-3d4c1d5b42a6"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("92ad9d34-92bb-4c8d-96a1-bfa0893f0ebb"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("5896e5c5-f49a-427a-963a-155ef9aa0ec9"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3cdc4392-fca1-4cf8-af38-5b2cb6606943"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7744539e-7606-43ab-8cb6-312a8d789917"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e11b3d4c-814f-44e9-849f-39216a77bfc0"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("6d8e0450-1cfb-473a-9cab-bb48d844f1aa"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a19dbd1d-912a-47fb-a4a7-fedff96dfe59"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("001e50bd-a5c7-45ac-bf90-9ac1759c9fa6"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("76b985e1-64a9-4d79-8707-a34392b8e29f"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("1c6e957d-8b11-46c0-9363-8e75fa64cf19"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("29cffa2e-fd73-4b90-a6f5-6261548c0cb8"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("d4e71a46-1747-4baa-aed2-fd9ae11d9160"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3a42b95e-207b-43b9-ac02-3abd30f78e71"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("408bfec6-c02b-4df6-9874-35a82ad75872"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("f80cefdc-ad3c-4c60-91de-9e46fdd7a1a9"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("bcc92ece-75c4-454e-89cf-6766aa078753"),
                            Date = new DateOnly(2026, 10, 6),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("8308b390-7dcb-4795-a8c2-4f135eec6ea4"),
                            Date = new DateOnly(2026, 10, 7),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("dbe6a1d8-cd0e-487f-814f-0b36c2918ca6"),
                            Date = new DateOnly(2026, 10, 8),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("732bffc3-44ab-401d-bd45-85cb781e0e89"),
                            Date = new DateOnly(2026, 10, 9),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7b99d311-9af6-4a1a-b684-29e9036595f7"),
                            Date = new DateOnly(2026, 10, 10),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7fb4e69a-87a5-4d05-8509-d0401b5822c3"),
                            Date = new DateOnly(2026, 10, 11),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e845e0c0-3aaf-46d9-a9ff-feff94640f26"),
                            Date = new DateOnly(2026, 10, 12),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalHistorySummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            BloodGroup = "O+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 38, 27, 886, DateTimeKind.Utc).AddTicks(4920),
                            DateOfBirth = new DateOnly(1985, 3, 12),
                            FullName = "Sarah Jenkins",
                            IsActive = true,
                            MedicalHistorySummary = "No known allergies. Previous appendectomy."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            BloodGroup = "A-",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 38, 27, 886, DateTimeKind.Utc).AddTicks(4930),
                            DateOfBirth = new DateOnly(1972, 11, 5),
                            FullName = "Marcus Thorne",
                            IsActive = true,
                            MedicalHistorySummary = "Type 2 Diabetes, Hypertension."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            BloodGroup = "B+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 38, 27, 886, DateTimeKind.Utc).AddTicks(4930),
                            DateOfBirth = new DateOnly(1990, 7, 22),
                            FullName = "Emily Chen",
                            IsActive = true,
                            MedicalHistorySummary = "Asthma, treated with inhalers."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            BloodGroup = "O-",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 38, 27, 886, DateTimeKind.Utc).AddTicks(4940),
                            DateOfBirth = new DateOnly(1950, 1, 30),
                            FullName = "David Alaba",
                            IsActive = true,
                            MedicalHistorySummary = "Coronary artery disease, pacemaker fitted 2018."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BloodGroup = "AB+",
                            CreatedAt = new DateTime(2026, 10, 5, 7, 38, 27, 886, DateTimeKind.Utc).AddTicks(4940),
                            DateOfBirth = new DateOnly(2005, 9, 14),
                            FullName = "Fiona Gallagher",
                            IsActive = true,
                            MedicalHistorySummary = "None."
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSafetyCheckResult")
                        .HasColumnType("text");

                    b.Property<string>("AiSafetyStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("IssuedByDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("NotificationChannel")
                        .HasColumnType("text");

                    b.Property<string>("NotificationFailureReason")
                        .HasColumnType("text");

                    b.Property<int>("NotificationRetryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageAttachments");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TentativeAppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("TriageRecords");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AgentWorkflowStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SymptomsAtReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TriageRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowStateId");

                    b.HasIndex("TriageRecordId");

                    b.ToTable("TriageReviewHistories");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 38, 27, 886, DateTimeKind.Utc).AddTicks(4860),
                            Email = "admin@careflow.ai",
                            Password = "password",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 38, 27, 886, DateTimeKind.Utc).AddTicks(4870),
                            DoctorId = new Guid("22222222-2222-2222-2222-222222222220"),
                            Email = "doctor@careflow.ai",
                            Password = "password",
                            Role = "Doctor",
                            Username = "doctor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 10, 5, 7, 38, 27, 886, DateTimeKind.Utc).AddTicks(4880),
                            Email = "staff@careflow.ai",
                            Password = "password",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("OccupiedBeds")
                        .HasColumnType("integer");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Capacity = 50,
                            OccupiedBeds = 45,
                            WardNumber = "G-01",
                            WardType = "General"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Capacity = 15,
                            OccupiedBeds = 12,
                            WardNumber = "I-01",
                            WardType = "ICU"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Capacity = 30,
                            OccupiedBeds = 20,
                            WardNumber = "M-01",
                            WardType = "Maternity"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacity = 25,
                            OccupiedBeds = 10,
                            WardNumber = "P-01",
                            WardType = "Pediatrics"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "PatientProfile")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientProfile");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.AgentWorkflowState", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("AgentWorkflows")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Appointment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.DoctorAvailability", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PrescriptionItem", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageAttachment", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany()
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.TriageAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageReviewHistory", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.AgentWorkflowState", "AgentWorkflowState")
                        .WithMany()
                        .HasForeignKey("AgentWorkflowStateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareFlowAI.API.Models.TriageRecord", "TriageRecord")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("TriageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflowState");

                    b.Navigation("TriageRecord");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.TriageRecord", b =>
                {
                    b.Navigation("AgentWorkflows");

                    b.Navigation("ReviewHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
