// <auto-generated />
using System;
using CareFlowAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareFlowAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923160608_AddUsersAndSeed")]
    partial class AddUsersAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalHistorySummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            BloodGroup = "O+",
                            CreatedAt = new DateTime(2026, 9, 23, 16, 6, 7, 376, DateTimeKind.Utc).AddTicks(9277),
                            DateOfBirth = new DateOnly(1985, 3, 12),
                            FullName = "Sarah Jenkins",
                            MedicalHistorySummary = "No known allergies. Previous appendectomy."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            BloodGroup = "A-",
                            CreatedAt = new DateTime(2026, 9, 23, 16, 6, 7, 376, DateTimeKind.Utc).AddTicks(9291),
                            DateOfBirth = new DateOnly(1972, 11, 5),
                            FullName = "Marcus Thorne",
                            MedicalHistorySummary = "Type 2 Diabetes, Hypertension."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            BloodGroup = "B+",
                            CreatedAt = new DateTime(2026, 9, 23, 16, 6, 7, 376, DateTimeKind.Utc).AddTicks(9299),
                            DateOfBirth = new DateOnly(1990, 7, 22),
                            FullName = "Emily Chen",
                            MedicalHistorySummary = "Asthma, treated with inhalers."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            BloodGroup = "O-",
                            CreatedAt = new DateTime(2026, 9, 23, 16, 6, 7, 376, DateTimeKind.Utc).AddTicks(9303),
                            DateOfBirth = new DateOnly(1950, 1, 30),
                            FullName = "David Alaba",
                            MedicalHistorySummary = "Coronary artery disease, pacemaker fitted 2018."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BloodGroup = "AB+",
                            CreatedAt = new DateTime(2026, 9, 23, 16, 6, 7, 376, DateTimeKind.Utc).AddTicks(9309),
                            DateOfBirth = new DateOnly(2005, 9, 14),
                            FullName = "Fiona Gallagher",
                            MedicalHistorySummary = "None."
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Password = "password",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Password = "password",
                            Role = "Doctor",
                            Username = "doctor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Password = "password",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("OccupiedBeds")
                        .HasColumnType("integer");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Capacity = 50,
                            OccupiedBeds = 45,
                            WardNumber = "G-01",
                            WardType = "General"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Capacity = 15,
                            OccupiedBeds = 12,
                            WardNumber = "I-01",
                            WardType = "ICU"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Capacity = 30,
                            OccupiedBeds = 20,
                            WardNumber = "M-01",
                            WardType = "Maternity"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacity = 25,
                            OccupiedBeds = 10,
                            WardNumber = "P-01",
                            WardType = "Pediatrics"
                        });
                });

            modelBuilder.Entity("CareFlowAI.API.Models.Admission", b =>
                {
                    b.HasOne("CareFlowAI.API.Models.PatientProfile", "PatientProfile")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlowAI.API.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientProfile");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CareFlowAI.API.Models.PatientProfile", b =>
                {
                    b.Navigation("Admissions");
                });
#pragma warning restore 612, 618
        }
    }
}
